from pathlib import Path
from html import escape
from urllib.parse import quote

root=Path(__file__).parent/'dist'
nav=[('O Refúgio','refugio'),('Experiências','experiencias'),('Gastronomia','gastronomia'),('Autocuidado','autocuidado'),('Domingos Martins','domingos-martins')]
phone='5527998787576'
wa=lambda msg:'https://wa.me/'+phone+'?text='+quote(msg)
reserve=wa('Olá, Tríade. Gostaria de consultar a disponibilidade para uma estadia a dois.')
image_names={1:'suite',2:'banheira',6:'caminho',9:'mesa',10:'risoto',11:'frutos-do-mar',12:'sala'}
def img(n,width=None):
 if n in image_names:
  wide=n in (1,2,6,9,12)
  width=width or (1920 if wide else 1280)
  return f'/assets/triade-{image_names[n]}-{width}.webp'
 return '/assets/fotos_triade-hospedagem-%02d.%s'%(n,'webp' if n<=9 else 'jpg')
def picture(n,alt,cls=''):
 if n in image_names:
  widths=(960,1920,3840) if n in (1,2,6,9,12) else (640,1280,2160)
  srcset=', '.join(f'{img(n,w)} {w}w' for w in widths)
  return f'<img class="{cls}" src="{img(n)}" srcset="{srcset}" sizes="100vw" alt="{escape(alt)}" loading="lazy" decoding="async">'
 return f'<img class="{cls}" src="{img(n)}" alt="{escape(alt)}" loading="lazy" decoding="async">'
def link(label,href,cls='text-link'):
 return f'<a class="{cls}" href="{href}">{label}<span aria-hidden="true">↗</span></a>'
def header():
 items=''.join(f'<a href="/{slug}/">{label}</a>' for label,slug in nav)
 return f'''<header class="site-header" id="site-header"><a class="brand" href="/" aria-label="Tríade — início"><img src="/assets/triade-logo.svg" alt="Tríade Hospedagem Boutique"></a><nav class="desktop-nav" aria-label="Navegação principal">{items}</nav><a class="header-book" href="/reservas/">Planejar estadia <span aria-hidden="true">↗</span></a><button class="menu-toggle" aria-label="Abrir menu" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span></button></header><nav class="mobile-menu" id="mobile-menu" aria-label="Navegação móvel"><a href="/">Início</a>{items}<a href="/reservas/">Planejar estadia</a><a href="/perguntas-frequentes/">Perguntas frequentes</a></nav>'''
def footer():
 return f'''<footer class="footer"><div><a class="footer-brand" href="/">TRÍADE</a><p>Hospitalidade privada para dois.<br>Domingos Martins, Espírito Santo.</p></div><div><span class="eyebrow">Explore</span><a href="/refugio/">O Refúgio</a><a href="/experiencias/">Experiências</a><a href="/gastronomia/">Gastronomia</a><a href="/autocuidado/">Autocuidado</a></div><div><span class="eyebrow">Converse conosco</span><a href="/reservas/">Reservas</a><a href="/perguntas-frequentes/">Perguntas frequentes</a><a href="https://www.instagram.com/triadehospedagem/" target="_blank" rel="noopener">Instagram ↗</a><a href="{reserve}" target="_blank" rel="noopener">WhatsApp ↗</a></div><div class="footer-bottom"><span>© 2026 Tríade Hospedagem Boutique</span><span>Um tempo só de vocês.</span></div></footer>'''
def cta(title='Seu próximo capítulo começa aqui.',text='Conte-nos quando deseja vir. Cuidaremos dos detalhes da sua estadia.',label='Consultar disponibilidade'):
 return f'<section class="closing-cta reveal"><span class="eyebrow">A sua estadia</span><h2>{title}</h2><p>{text}</p>{link(label,"/reservas/","button-light")}</section>'
def page(title,description,body,slug='',ogtype='website'):
 canonical='https://triadehospedagem.com.br/'+(slug+'/' if slug else '')
 return f'''<!doctype html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#17211e"><title>{escape(title)} | Tríade Hospedagem Boutique</title><meta name="description" content="{escape(description)}"><link rel="canonical" href="{canonical}"><link rel="icon" href="/assets/cropped-favicon-192x192.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Italiana&family=DM+Sans:wght@400;500;600&family=Manrope:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="/style.css"><script type="application/ld+json">{{"@context":"https://schema.org","@type":"LodgingBusiness","name":"Tríade Hospedagem Boutique","url":"https://triadehospedagem.com.br/","telephone":"+55 27 99878-7576","address":{{"@type":"PostalAddress","addressLocality":"Domingos Martins","addressRegion":"ES","addressCountry":"BR"}},"sameAs":["https://www.instagram.com/triadehospedagem/"]}}</script><script defer src="/app.js"></script></head><body>{header()}<main id="content">{body}</main>{footer()}</body></html>'''
def inner_hero(kicker,title,lede,n,alt):
 return f'<section class="inner-hero"><div class="inner-hero-image">{picture(n,alt)}</div><div class="inner-hero-shade"></div><div class="inner-hero-copy"><span class="eyebrow">{kicker}</span><h1>{title}</h1><p>{lede}</p></div><span class="vertical-note">TRÍADE · DOMINGOS MARTINS</span></section>'
def split(kicker,title,text,n,alt,href=None,label=None,reverse=False):
 action=link(label,href) if href else ''
 return f'<section class="split-section {"reverse" if reverse else ""}"><div class="split-image reveal">{picture(n,alt)}</div><div class="split-copy reveal"><span class="eyebrow">{kicker}</span><h2>{title}</h2><p>{text}</p>{action}</div></section>'

home=f'''<div class="preloader" aria-hidden="true"><span>TRÍADE</span><div class="preloader-line"></div><small>HOSPEDAGEM BOUTIQUE</small></div><section class="hero" id="hero"><div class="hero-media"><video class="hero-video" muted playsinline preload="metadata" poster="{img(1)}"><source src="/assets/triade-hero.mp4" type="video/mp4"></video><div class="hero-fallback" style="background-image:url('{img(1)}')"></div></div><div class="hero-shade"></div><div class="hero-content"><span class="eyebrow">Domingos Martins · Espírito Santo</span><h1>Um refúgio inteiro.<br><em>Apenas para dois.</em></h1><p>Em meio às montanhas de Domingos Martins, a Tríade recebe um único casal por vez para viver dias de privacidade, silêncio, natureza, gastronomia e cuidado.</p>{link('Descobrir a Tríade','/refugio/','button-light')}</div><div class="hero-bottom"><span>Desça para sentir</span><span class="scroll-rule"></span><span>01 / 04</span></div></section>
<section class="manifesto section-pad"><div class="manifesto-index eyebrow reveal">01 / Só vocês</div><div class="manifesto-copy reveal"><h2>Durante a estadia, a Tríade pertence a um único casal.</h2><p>A paisagem, o silêncio e o tempo se abrem para que cada instante aconteça no próprio ritmo.</p>{link('Conhecer o refúgio','/refugio/')}</div></section>
<section class="image-interlude"><div class="parallax-photo">{picture(6,'Caminho iluminado entre a vegetação da Tríade')}</div><div class="interlude-copy reveal"><span class="eyebrow">O Refúgio</span><h2>Estar perto de tudo<br>o que importa.</h2></div></section>
<section class="editorial-grid section-pad"><div class="editorial-lead reveal"><span class="eyebrow">02 / A experiência</span><h2>Há outra forma<br>de sentir o tempo.</h2><p>A luz atravessa o vidro. O rio marca as horas. O descanso não precisa de roteiro.</p>{link('Viver a experiência','/experiencias/')}</div><div class="editorial-photo reveal">{picture(1,'Suíte da Tríade com banheira ao fundo')}</div><div class="editorial-side reveal">{picture(2,'Banheira de imersão da Tríade')}<p>Uma casa para estar presente, sem pressa de chegar a outro lugar.</p></div></section>
<section class="ritual-section"><div class="ritual-intro section-pad reveal"><span class="eyebrow">03 / Rituais da Tríade</span><h2>O cuidado está<br>nos detalhes.</h2></div><div class="ritual-cards"><a href="/gastronomia/" class="ritual-card"><div class="ritual-photo">{picture(9,'Mesa com pratos preparados na Tríade')}</div><div class="ritual-caption"><span>01 / A Mesa</span><h3>O prazer de ficar.</h3><span aria-hidden="true">↗</span></div></a><a href="/autocuidado/" class="ritual-card"><div class="ritual-photo">{picture(2,'Banheira de imersão na suíte')}</div><div class="ritual-caption"><span>02 / O Cuidado</span><h3>O tempo de sentir.</h3><span aria-hidden="true">↗</span></div></a></div></section>
<section class="quote-section section-pad reveal"><span class="eyebrow">A essência</span><blockquote>Uma estadia feita de presença.<br>Da liberdade de não precisar sair.</blockquote><div class="quote-line"></div><p>Arquitetura, gastronomia e cuidado em uma mesma experiência, dedicada a dois.</p></section>
<section class="destination section-pad"><div class="destination-copy reveal"><span class="eyebrow">04 / O destino</span><h2>Domingos Martins,<br>por outro ângulo.</h2><p>Nas Montanhas Capixabas, a natureza convida a desacelerar. Aqui, o destino também pode ser vivido sem sair do refúgio.</p>{link('Explorar o destino','/domingos-martins/')}</div><div class="destination-image reveal">{picture(6,'Caminho em meio à vegetação na Tríade')}</div></section>{cta()}'''

refugio=inner_hero('01 / O Refúgio','Um lugar inteiro<br>para dois.','Um espaço reservado a um único casal, para viver a montanha com privacidade e liberdade.',1,'Suíte da Tríade')+split('A arquitetura','A natureza faz parte da casa.','A arquitetura em vidro aproxima o interior da mata. O rio, a luz e a paisagem mudam ao longo do dia e transformam a maneira de estar aqui.',12,'Sala de estar da Tríade')+split('A privacidade','O privilégio de estar só.','Durante a estadia, o refúgio é dedicado a vocês. Escolham quando acordar, quando se sentar à mesa e como viver cada intervalo do dia.',2,'Banheira da suíte privativa da Tríade',reverse=True)+'''<section class="details-section section-pad"><span class="eyebrow">A casa</span><h2>Conforto sem distrações.</h2><div class="details-grid"><p>Suíte com cama king size</p><p>Banheira de imersão</p><p>Arquitetura em vidro</p><p>Cozinha à beira do rio</p><p>Sala de descanso</p><p>Ambientes climatizados</p></div><small>Para informações completas sobre estrutura e condições da estadia, converse com a equipe.</small></section>'''+cta()
experiencias=inner_hero('02 / Experiências','O tempo muda<br>quando é de vocês.','Uma estadia para descobrir o prazer de fazer menos e sentir mais.',6,'Caminho entre a vegetação da Tríade')+'''<section class="intro-text section-pad reveal"><span class="eyebrow">No seu ritmo</span><h2>Não há um roteiro a seguir.</h2><p>Talvez o dia comece com a luz entrando pela janela. Talvez a tarde seja feita de água, conversa e silêncio. A Tríade acompanha o tempo de vocês.</p></section>'''+split('A Mesa','Uma noite que fica na memória.','Menus autorais e a Noite com o Chef levam o prazer da mesa ao próprio refúgio. O jantar acontece sem que vocês precisem deixar a privacidade da estadia.',9,'Mesa com pratos da Tríade','/gastronomia/','Conhecer a gastronomia')+split('O Cuidado','O descanso pode ir mais longe.','Massoterapia e escalda-pés ampliam o tempo de pausa, com experiências combinadas para a estadia.',2,'Banheira de imersão da Tríade','/autocuidado/','Explorar o autocuidado',True)+cta('O que vocês gostariam de viver?','Compartilhe a ocasião e as suas preferências. A equipe ajuda a planejar cada detalhe.','Planejar minha estadia')
gastronomia=inner_hero('03 / A Mesa','A experiência<br>continua à mesa.','A gastronomia é parte da experiência de estar na Tríade.',9,'Mesa com pratos preparados na Tríade')+'''<section class="intro-text section-pad reveal"><span class="eyebrow">A gastronomia</span><h2>Uma experiência para ser vivida aqui.</h2><p>Ingredientes, preparo e serviço encontram a intimidade do refúgio. O prazer não está apenas no prato: está em não precisar interromper o momento para estar à mesa.</p></section>'''+split('Noite com o Chef','Uma noite preparada diante de vocês.','Uma noite intimista, com preparo ao vivo e menu autoral. O chef, os aromas e a mesa compõem um ritual dedicado ao casal.',10,'Prato servido na Tríade')+split('Menus autorais','Sabores com identidade.','Os menus são pensados para transformar a refeição em parte da viagem, valorizando ingredientes e referências das Montanhas Capixabas.',11,'Prato de frutos do mar da Tríade',reverse=True)+'''<section class="statement section-pad reveal"><span class="eyebrow">À sua maneira</span><h2>O melhor horário é o de vocês.</h2><p>Consulte as opções gastronômicas disponíveis para a data da sua estadia, valores e necessidades alimentares no momento da reserva.</p></section>'''+cta('Reserve um tempo para a mesa.','Converse com a equipe para conhecer os menus e planejar a experiência gastronômica.','Consultar experiências')
autocuidado=inner_hero('04 / O Cuidado','O descanso também<br>pode começar pelo corpo.','Rituais de cuidado para aprofundar o descanso sem sair do refúgio.',2,'Banheira da suíte Tríade')+'''<section class="intro-text section-pad reveal"><span class="eyebrow">Cuidado e presença</span><h2>Há dias que pedem menos movimento.</h2><p>O silêncio, a água e os pequenos gestos criam espaço para descansar. As experiências de autocuidado chegam até vocês e acompanham o ritmo da estadia.</p></section>'''+split('Massoterapia','Um momento para desacelerar ainda mais.','Uma pausa dedicada ao corpo, no ambiente reservado da Tríade. Consulte as modalidades e horários disponíveis ao planejar sua viagem.',1,'Suíte privativa da Tríade')+split('Escalda-pés','Um pequeno ritual de pausa.','A água morna e a atenção aos detalhes convidam a desacelerar ainda mais.',6,'Caminho em meio à natureza da Tríade',reverse=True)+cta('Cuide do seu tempo.','Conte-nos quais rituais deseja incluir. A equipe orienta disponibilidade e condições.','Planejar os rituais')
destino=inner_hero('05 / O Destino','Montanhas por<br>todos os lados.','Domingos Martins, no Espírito Santo, é o cenário de uma estadia feita para se aproximar da natureza.',6,'Caminho entre a vegetação na Tríade')+'''<section class="intro-text section-pad reveal"><span class="eyebrow">Montanhas Capixabas</span><h2>O destino começa ao redor.</h2><p>A paisagem muda com a luz. O rio traz outra medida para as horas. Na Tríade, a experiência de Domingos Martins começa pela liberdade de simplesmente estar.</p></section>'''+split('A região','Explore quando quiser.','A região de Domingos Martins reúne natureza, gastronomia e caminhos para descobrir. Nossa equipe pode compartilhar orientações para sua chegada e sugestões para a estadia.',6,'Trilha entre a vegetação da Tríade')+cta('Sua montanha. Seu tempo.','Planeje a estadia e descubra a Tríade no ritmo de vocês.','Consultar disponibilidade')
faqitems=[('A hospedagem é reservada exclusivamente para um casal?','Sim. A Tríade recebe um único casal por estadia, com o refúgio reservado para vocês.'),('Onde fica a Tríade?','A Tríade fica em Domingos Martins, nas Montanhas Capixabas, Espírito Santo. As orientações de acesso são compartilhadas durante o planejamento da estadia.'),('Como consultar datas e valores?','Envie as datas desejadas pelo WhatsApp. A equipe informará disponibilidade, valores e condições aplicáveis.'),('Como funciona a Noite com o Chef?','É uma experiência gastronômica no próprio refúgio, organizada mediante consulta e agendamento. Menus, valores e disponibilidade são apresentados pela equipe.'),('Há experiências de autocuidado?','Sim. Consulte com antecedência as opções de massoterapia e escalda-pés, horários e valores.'),('O que está incluído na diária?','Os itens incluídos e as experiências opcionais são detalhados pela equipe antes da confirmação da reserva.'),('Qual é o horário de check-in e check-out?','Os horários e condições da reserva são informados pela equipe ao consultar a disponibilidade.'),('A Tríade aceita crianças ou animais de estimação?','A proposta da Tríade é uma estadia para um casal. Consulte a equipe sobre as políticas vigentes antes de reservar.')]
faq=inner_hero('Informações essenciais','Antes de chegar,<br>tudo claro.','Respostas para planejar sua estadia com tranquilidade.',12,'Sala de estar da Tríade')+'<section class="faq-section section-pad"><span class="eyebrow">Perguntas frequentes</span><h2>O que você gostaria de saber?</h2><div class="faq-list">'+''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>' for q,a in faqitems)+'</div></section>'+cta('Ainda tem uma pergunta?','Nossa equipe pode ajudar você a planejar a estadia.', 'Conversar sobre a estadia')
reservas=inner_hero('Reservas','Um refúgio. Um casal.<br>Uma estadia por vez.','Diga-nos quando deseja vir e o que gostaria de viver. Cada detalhe pode ser planejado no seu tempo.',1,'Suíte privativa da Tríade')+f'''<section class="reservation section-pad"><div class="reservation-copy reveal"><span class="eyebrow">Planeje sua estadia</span><h2>Vamos cuidar dos detalhes.</h2><p>A Tríade recebe um casal por estadia. Compartilhe as datas desejadas e as experiências que imagina para esse tempo a dois. A equipe retornará com disponibilidade, valores e condições.</p><ul><li>01 <span>Escolha as datas</span></li><li>02 <span>Conte o que deseja viver</span></li><li>03 <span>Receba as condições da estadia</span></li></ul></div><form class="reservation-form reveal" id="reservation-form"><label for="guest">Seu nome</label><input id="guest" name="guest" autocomplete="name" required placeholder="Como podemos chamar você?"><div class="form-row"><div><label for="arrival">Chegada</label><input id="arrival" name="arrival" type="date" required></div><div><label for="departure">Saída</label><input id="departure" name="departure" type="date" required></div></div><label for="interest">O que você gostaria de viver?</label><select id="interest" name="interest"><option value="Estadia">A estadia</option><option value="Estadia e gastronomia">Estadia e gastronomia</option><option value="Estadia e autocuidado">Estadia e autocuidado</option><option value="Uma experiência completa">Uma experiência completa</option></select><label for="message">Conte-nos um pouco mais (opcional)</label><textarea id="message" name="message" rows="3" placeholder="Uma ocasião especial, preferências ou dúvidas"></textarea><button type="submit" class="button-dark">Consultar pelo WhatsApp <span aria-hidden="true">↗</span></button><p class="form-note">A consulta abrirá uma conversa com a equipe no WhatsApp. A reserva será confirmada após o atendimento.</p></form></section><section class="reservation-end section-pad reveal"><span class="eyebrow">Contato direto</span><p>Prefere começar com uma mensagem?</p>{link('Conversar com a Tríade',reserve)}</section>'''

pages={
 '':('Um refúgio inteiro. Apenas para dois','Hospedagem boutique privada para um casal em Domingos Martins. Natureza, gastronomia e cuidado no seu tempo.',home),
 'refugio':('O Refúgio','Conheça o refúgio privado da Tríade: arquitetura em vidro, natureza e uma estadia reservada a um casal em Domingos Martins.',refugio),
 'experiencias':('Experiências','Viva a Tríade no seu ritmo: descanso, gastronomia e rituais de cuidado em uma hospedagem privada para dois.',experiencias),
 'gastronomia':('Gastronomia','Menus autorais e Noite com o Chef no refúgio privado da Tríade em Domingos Martins.',gastronomia),
 'autocuidado':('Autocuidado','Massoterapia e escalda-pés para ampliar o descanso durante sua estadia na Tríade.',autocuidado),
 'domingos-martins':('Domingos Martins','Conheça a Tríade em Domingos Martins, Espírito Santo, entre a natureza das Montanhas Capixabas.',destino),
 'reservas':('Reservas','Consulte disponibilidade para uma estadia a dois na Tríade Hospedagem Boutique, em Domingos Martins.',reservas),
 'perguntas-frequentes':('Perguntas frequentes','Informações sobre exclusividade, reservas, gastronomia, autocuidado e estadia na Tríade.',faq)
}
for slug,(title,description,body) in pages.items():
 target=root/slug/'index.html' if slug else root/'index.html'
 target.parent.mkdir(parents=True,exist_ok=True)
 target.write_text(page(title,description,body,slug),encoding='utf-8')
(root/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://triadehospedagem.com.br/sitemap.xml\n')
(root/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://triadehospedagem.com.br/'+(s+'/' if s else '')+'</loc></url>' for s in pages)+'</urlset>')
